

<?php

?>

<?php echo $result; ?>

<form action="post" enctype="multipart/form-data">
    <input type="file" name="temp_file" id="upload-rss"/>
</form>

<div class="article" id="page-content-wrapper" >
    <div class="container">
        <div class="header clearfix">
            <div class="pull-left btn-menu-wrapper">
                <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><i class="fa fa-bars"></i></a>
            </div>
            <div class="pull-right">
                <a href="#" class="btn btn-default"><i class="fa fa-check"></i></a>
                <a href="#" class="btn btn-default"><i class="fa fa-repeat"></i></a>
            </div>
        </div>
        <!-- 블로그 테마-->
        <div class="section row blog-group">
            <div class="post-title-group">
                <h3>Simple Sidebar</h3>
                <span class="post-title-unread">15 unread articles</span>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample1.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>
                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample2.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>

                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/thumb.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>

                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample4.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>

                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample5.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>

                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample6.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>

                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample7.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>

                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample8.jpg">
                        </div>
                    </div>
                    <div class="col-xs-10 blog-body">
                        <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                        <p>111111</p>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>

                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-2 blog-left">
                        <div class="clip">
                            <img src="img/sample9.jpg">
                        </div>
                    </div>
                </a>
                    <div class="col-xs-10 blog-body">
                        <a href="#">
                            <div class="">
                                <h4>Dramatically Raise the Value of Any Piece of Content</h4>
                                <p>111111</p>
                            </div>
                        </a>
                        <div class="meta">
                            <span class="label label-default">searchenginewatch.com</span>
                            <span class="time">1 hour ago</span>
                            <div class=""><button>hide</button> / <button>save</button></div>
                        </div>
                    </div>


            </div>

        </div>



        <!-- 갤러리 테마 -->
        <div class="section row gally">
            <div class="post-title-group">
                <h3>Simple Sidebar</h3>
                <span class="post-title-unread">15 unread articles</span>
            </div>
            <div class="row">
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample1.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample2.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/thumb.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample4.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample5.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample6.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample7.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample8.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample9.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
                <div class="col-xs-3 item">
                    <a href="#">
                        <div class="clip">
                            <img src="img/sample2.jpg">
                        </div>
                        <h4 class="title">Dramatically Raise the Value of Any Piece of Content</h4>
                        <div class="meta">

                            <span class="time">1 hour ago</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <div class="section row list-group">

            <div class="post-title-group">
                <h3>Simple Sidebar</h3>
                <span class="post-title-unread">15 unread articles</span>
            </div>
            <div class="clearfix item row">
                <a href="#">
                    <div class="col-xs-12 list-body">
                        <h4>토요일 오전</h4>
                        <p>20분 남짓 짧은 시간. 봉하마을에 다녀왔다. 생각 같아선 한 두 시간 있고 싶었지만, 함께한 이들과 일정을 맞추느라 어쩔 수 없이 잠시 눈도장만 찍고 발걸음을 돌려야 했다. 사진으로 본 것보다 소박하게 조성된 故 노무현 前 대통령의 묘소. 그 앞에서 묵념을 하고 한참 묘소만 바라보았다. 스피커에서 흘러나오는 상록수와 아침이슬 연주곡, 그리고 여기저기 남겨진 고인의 흔적들. 그 흔적들을 따라가는데 울컥하고 눈물이 쏟아지..</p>
                        <div class="meta">
                            <span class="author">by searchenginewatch.com</span>
                            <span class="">/</span>
                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="clearfix item row">
                <a hrer="#">
                    <div class="col-xs-12 list-body">
                        <h4>부끄러움</h4>
                        <p>20분 남짓 짧은 시간. 봉하마을에 다녀왔다. 생각 같아선 한 두 시간 있고 싶었지만, 함께한 이들과 일정을 맞추느라 어쩔 수 없이 잠시 눈도장만 찍고 발걸음을 돌려야 했다. 사진으로 본 것보다 소박하게 조성된 故 노무현 前 대통령의 묘소. 그 앞에서 묵념을 하고 한참 묘소만 바라보았다. 스피커에서 흘러나오는 상록수와 아침이슬 연주곡, 그리고 여기저기 남겨진 고인의 흔적들. 그 흔적들을 따라가는데 울컥하고 눈물이 쏟아지..</p>
                        <div class="meta">
                            <span class="author">by searchenginewatch.com</span>
                            <span class="">/</span>
                            <span class="time">1 hour ago</span>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    </div>
</div>






