


<!-- Sidebar -->
<div id="sidebar-wrapper">
    <div class="btn-add-wrapper">
        <a href="#" data-toggle="modal" data-target="#modal-sample-form"><i class="fa fa-plus"></i> Add Content</a>
    </div>
    <ul id="menu">
        <li class="active">
            <a href="#"><i class="fa fa-th"></i> All <span class="fa arrow"></span></a>
            <ul class="collapse in">
                <?php foreach($user_menu as $key=>$val): ?>
<!--                <li><a href="#" data-rss-url="http://uiandwe.tistory.com/rss">uiandwe</a></li>-->
<!--                <li><a href="#">item 0.2</a></li>-->
<!--                <li><a href="http://onokumus.com">onokumus</a></li>-->
<!--                <li><a href="#">item 0.4</a></li>-->

                    <li><a href="#" data-rss-url="<?php echo $val->link ?>"><?php echo $val->title ?></a></li>
                <?php endforeach ?>
            </ul>
        </li>
<!--        <li>-->
<!--            <a href="#">Menu 1 <span class="glyphicon arrow"></span></a>-->
<!--            <ul class="collapse">-->
<!--                <li><a href="#">item 1.1</a></li>-->
<!--                <li><a href="#">item 1.2</a></li>-->
<!--                <li>-->
<!--                    <a href="#">Menu 1.3 <span class="fa arrow"></span></a>-->
<!--                    <ul class="collapse">-->
<!--                        <li><a href="#">item 1.3.1</a></li>-->
<!--                        <li><a href="#">item 1.3.2</a></li>-->
<!--                        <li><a href="#">item 1.3.3</a></li>-->
<!--                        <li><a href="#">item 1.3.4</a></li>-->
<!--                    </ul>-->
<!--                </li>-->
<!---->
<!--            </ul>-->
<!--        </li>-->
    </ul>

    <ul id="menu1">

    </ul>

    <div class="user-info">
        <img class="user-avatar" src="/img/user-default.png" alt="user profile image">
        <p class="email"><?php echo $logged_user->email ?></p>
        <a href="#" class="logout">Logout</a>
    </div>
</div>
<!-- /#sidebar-wrapper -->

<?php

?>

<div class="article" id="page-content-wrapper" >
    <div class="container">
        <div class="col-xs-10" id="container_warpper">
            <div class="header clearfix">
                <div class="pull-left">
                    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><i class="fa fa-bars"></i></a>
                </div>
                <div class="pull-right btn-menu-wrapper">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle"
                                data-toggle="dropdown"> <i class="fa fa-th"></i> <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu" >
                            <li><a href="#" data-menu-type="blog">blog</a></li>
                            <li><a href="#" data-menu-type="gally">gally</a></li>
                            <li><a href="#" data-menu-type="list">list</a></li>
<!--                            <li class="divider"></li>-->
<!--                            <li><a href="#">Poke</a></li>-->
                        </ul>
                    </div>

<!--                    <a href="#" class="btn btn-default"><i class="fa fa-check"></i></a>-->
                    <a href="#" class="btn btn-default"><i class="fa fa-repeat"></i></a>
                </div>
            </div>
            <input type="hidden" class="rss_url" value="">
            <input type="hidden" class="user-menu-id" value="">
            <input type="hidden" class="view_type" value="list">
<!--            <div class="section row list-group blog-group" id="rss_content" >-->
<!---->
<!--            </div>-->
<!--            <div class="section row list-group gally" id="rss_content" >-->
<!--            </div>-->
                <div class="section row list-group" id="rss_content" >
                </div>

        </div>

    </div>
</div>


<form class="modal fade" id="modal-sample-form" aria-hidden="true" action="/admin" method="post" enctype="multipart/form-data">
    <input type="hidden" name="sample_id" value="0" />
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Video form</h4>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="form-group col-xs-12">
                        <label for="sample-link" class="control-label">Set RSS / feed  url</label>
                        <input type="text" name="link" id="sample-link" value="" class="form-control" />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-xs-12">
                        <label for="sample-title" class="control-label">Import file</label>
                        <form action="post" enctype="multipart/form-data">
                            <input type="file" name="temp_file" id="upload-rss"/>
                        </form>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default">Save</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->



