<?php

if(!isset($is_share)) {
    $is_share = null;
}

if(!isset($notifications)) {
    $notifications = null;
}

?>

<!doctype html>
<html lang="ko">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Rss</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- font-awesome CSS -->
    <link href="css/font-awesome.css" rel="stylesheet">
    <link href="css/tree-style.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">
    <link href="css/rss.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <div id="jstree-proton-2" class="proton-demo">
                <ul>
                    <li data-jstree='{ "opened" : true }'>Root node (wholerow mode)
                        <ul >
                            <li>
                                <a href="#">
                                    <em>initially</em>
                                    <strong>selected</strong>
                                </a>
                            </li>
                            <li data-jstree='{ "icon" : "./assets/images/tree_icon.png" }'>custom icon URL</li>
                            <li data-jstree='{ "opened" : true }'>initially open
                                <ul>
                                    <li>Another node</li>
                                </ul>
                            </li>
                            <li data-jstree='{ "icon" : "glyphicon glyphicon-leaf" }'>Custom icon class (bootstrap)</li>
                        </ul>
                    </li>
                    <li><a href="http://www.jstree.com">Root node 2</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->


        <?php echo $this->getContent(); ?>

    <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <script src="js/jquery.form.min.js"></script>
    <script src="js/rss.js"></script>
    <script src="js/jstree.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>
</html>
